# 1. Base image
FROM node:20-alpine

# 2. Working directory
WORKDIR /app

# 3. Dependencies copy
COPY package*.json ./

# 4. Install dependencies
RUN npm install

# 5. Copy project files
COPY . .

# 6. Build Next.js app
RUN npm run build

# 7. Expose port
EXPOSE 3000

# 8. Start app
CMD ["npm", "run", "start"]